github:
  api_base: https://api.github.com
  rate_limit: 1.0
  max_retries: 3
  backoff_factor: 0.5

storage:
  base_path: data

paper:
  url_extraction_mode: llm

docs:
  max_depth: 1  # Default depth for documentation crawling
