name: corema
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Core dependencies
  - python-dotenv=1.0.1
  - requests=2.32.3
  - pyyaml=6.0.2
  - fire=0.7.0
  - pdfminer.six=20231228
  - beautifulsoup4=4.12.3
  - fake-useragent=1.4.0
  - gitpython=3.1.43
  - typing-extensions=4.12.2
  - openai=1.59.0
  - tiktoken=0.8.0
  - pandas=2.2.3
  - pyarrow=18.1.0
  # Analysis dependencies
  - scikit-learn=1.6.0
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - jupyter=1.1.1
  - plotnine=0.14.4
  - wordcloud=1.9.4
  # Development dependencies
  - pytest
  - pytest-cov
  - mypy
  - black
  - ruff
  - pre-commit
